version: "3.3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_DATABASE: 'checkAgro-dev'
      MYSQL_USER: 'usr-checkAgro'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3307'
    expose:
      # Opens port 3307 on the container
      - '3307'
      # Where our data will be persisted